const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 1200,
    img: './images/item-1.jpeg',
    desc: `Buttermilk Pancake have a light and spongy texture and their flavor only hints of the richness and tanginess that buttermilk offers.`,

  },
  {
    id: 2,
    title: 'Veggie Burgers',
    category: 'lunch',
    price: 1300,
    img: './images/item-2.jpeg',
    desc: `Veggie Burgers are convenient, filling, and can be a good source of fiber and protein. `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 600,
    img: './images/item-3.jpeg',
    desc: `Milkshake are made of milk which instantly makes us healthy.`,
  },
  {
    id: 4,
    title: 'whole Grains',
    category: 'breakfast',
    price: 2000,
    img: './images/item-4.jpeg',
    desc: `Whole grains contain antioxidants that protect your tissues from harmful inflammation. `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 2200,
    img: './images/item-5.jpeg',
    desc: `Full of fiber and lean protein it includes a range of highly detailed statues.  `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 1800,
    img: './images/item-6.jpeg',
    desc: `The oreos are infused into a creamy, rich pudding that is poked into a tender chokolate.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 800,
    img: './images/item-7.jpeg',
    desc: ` Viral single-origin coffee live-edge, pork belly cloud bread iceland . `,
  },
  {
    id: 8,
    title: 'American classic',
    category: 'lunch',
    price: 1200,
    img: './images/item-8.jpeg',
    desc: `American Classic is a family owned and operated distributer and manufacturer of frozen desserts. `,
  },
  {
    id: 9,
    title: 'Vanilla Shake',
    category: 'shakes',
    price: 1600,
    img: './images/item-9.jpeg',
    desc: `A smooth, rich and creamy treat for any time of the day.`,
  },
];
export default menu;
